proyecto_python/barberhouse/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = "barberhouse"

urlpatterns = [
    path('', views.inicio, name="inicio"),

    
    #contraseña
    
    
    
    
    #Roles
    path('roles/', views.roles, name="listarRoles"),
    path('crear_rol/', views.formularioRol, name="crear_Rol"),
    path('Guardar_rol/', views.guardarRol, name="guardar_Rol"),
    path('editar_rol/<int:id>', views.editarRol, name="editar_Rol"),
    path('actualizar_rol/', views.actualizarRol, name="actualizar_Rol"),
    path('eliminar:rol/<int:id>', views.eliminarRol, name="eliminar_Rol"),
    path('BuscarRol/',views.rolesBuscar, name="Buscar_rol"),


    #Login
    path('loginForm/',views.loginForm, name="loginForm"),
    path('login/',views.login, name="login"),
    path('loginCerrar/',views.loginCerrar, name="login_cerrar"),
    
    #Email
    path('enviarMail/',views.sendMail, name="Send_mail"),
    

    #usuarios
    path('usuarios/', views.usuarios, name="listarUsuarios"),
    path('crear_usuarios/', views.usuariosFormulario, name="crear_usuario"),
    path('crear_usuarios/', views.usuariosFormulario, name="registrar_cliente"),
    path('guardar_usuarios/', views.usuariosGuardar, name="guardar_usuario"),
    path('guardar_clientes/', views.clientesGuardar, name="guardar_cliente"),
    path('editar_usuarios/<int:id>', views.usuariosEditar, name="editar_usuario"),
    path('actualizar_usuarios/', views.usuariosActualizar, name="actualizar_usuario"),
    path('eliminar_usuarios/<int:id>', views.usuariosEliminar, name="eliminar_usuario"),
    path('BuscarUsuario/',views.usuariosBuscar, name="Buscar_usuario"),
    path('Perfil/',views.perfil, name="Perfil_Usuario"),
    path('ActualizarPerfil/',views.actualizarPerfil, name="actualizar_perfil"),

    #servicios
    path('servicios/', views.servicios, name="listarServicios"),
    path('crear_servicios/', views.serviciosFormulario, name="crear_servicio"),
    path('guardar_servicios/', views.serviciosGuardar, name="guardar_servicio"),
    path('editar_servicios/<int:id>', views.serviciosEditar, name="editar_servicio"),
    path('actualizar_servicios/', views.serviciosActualizar, name="actualizar_servicio"),
    path('eliminar_servicios/<int:id>', views.serviciosEliminar, name="eliminar_servicio"),
    
    #Citas
    path('citas/', views.citas, name="listarCitas"),
    path('crear_citas/', views.citasFormulario, name="crear_cita"),
    path('guardar_citas/', views.citasGuardar, name="guardar_cita"),
    path('editar_citas/<int:id>', views.citasEditar, name="editar_cita"),
    path('actualizar_citas/', views.citasActualizar, name="actualizar_cita"),
    path('eliminar_citas/<int:id>', views.citasEliminar, name="eliminar_cita"),
    
    #Promociones
    path('promociones/', views.promociones, name="listarPromociones"),
    path('crear_promociones', views.promocionesFormulario, name="crear_promocion"),
    path('guardar_promociones', views.promocionesGuardar, name="guardar_promocion"),
    path('editar_promociones/<int:id>', views.promocionesEditar, name="editar_promocion"),
    path('actualizar_promociones/', views.promocionesActualizar, name="actualizar_promocion"),
    path('eliminar_promociones/<int:id>', views.promocionesEliminar, name="eliminar_promocion"),

]

proyecto_python/proyecto_python/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('barberhouse/', include('barberhouse.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

proyecto_python/barberhouse/models.py
from django.db import models

# Create your models here.
class Rol(models.Model):
    nombre_rol = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_rol
    
class Usuarios(models.Model):
    cedula_usuario = models.IntegerField(primary_key = True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    correo = models.EmailField()
    clave = models.CharField(max_length=20)
    rol = models.ForeignKey(Rol, on_delete= models.DO_NOTHING, default=3)
    foto = models.ImageField(upload_to = 'barberhouse/fotos', default = 'barberhouse/fotos/default.png')

    
    def __str__(self):          
        return f"{self.nombre}"
    
class Promociones(models.Model):
    nombre_promocion = models.CharField(max_length=100)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    
    def __str__(self):
        return f"{self.nombre_promocion}"
    
class Servicios(models.Model):
    nombre_servicio = models.CharField(max_length=100)
    precio = models.IntegerField()
    promocion = models.ForeignKey(Promociones, on_delete= models.DO_NOTHING)
    empleado = models.ForeignKey(Usuarios, on_delete= models.DO_NOTHING)
    
    def __str__(self):
        return f"{self.nombre_servicio}"
    
class Citas(models.Model):
    fecha_cita = models.DateTimeField()
    usuarioCliente = models.ForeignKey(Usuarios, on_delete= models.DO_NOTHING, related_name = "usuarioCliente")
    usuarioEmpleado = models.ForeignKey(Usuarios, on_delete= models.DO_NOTHING, related_name = "usuarioEmpleado")
    
    
    def __str__(self):
        return f"{self.id} - {self.fecha_cita}"

class ServiciosCitas(models.Model):
    servicio = models.ForeignKey(Servicios, on_delete= models.DO_NOTHING)
    cita = models.ForeignKey(Citas, on_delete= models.DO_NOTHING)

    def __str__(self):
        return f"serv: {self.servicio} cita: {self.cita}"

proyecto_python/barberhouse/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import ServiciosCitas, Usuarios, Citas, Servicios, Promociones, Rol

# Mensajes tipo Cookie temporales
from django.contrib import messages

# Gestión de errores de base de datos
from django.db import IntegrityError

#Paginador
from django.core.paginator import Paginator

#Buscar
from django.db.models import Q

from .crypt import claveEncriptada
from django.core.mail import send_mail



#Almacenamiento y gestión de archivos o fotos
from django.core.files.storage import FileSystemStorage
from pathlib import Path
from os import remove, path 
BASE_DIR = Path(__file__).resolve().parent.parent

# Create your views here.

def inicio(request):
    return render(request, 'barberhouse/index.html')


def loginForm(request):
    return render(request,'barberhouse/login/login.html')

def login(request):
    try:
        correo = request.POST["correo"]
        clave = request.POST["clave"]

        # r = Rol.objects.all(nombre_rol = nombre_rol)
        
        u = Usuarios.objects.get(correo = correo, clave = clave)

        request.session["logueo"] = [u.cedula_usuario, u.nombre, u.apellido, u.rol.nombre_rol]

        return redirect('barberhouse:inicio')
    except:
        messages.warning(request,"no se han enviado datos")
        return redirect('barberhouse:inicio')

def loginCerrar(request):
    try:
        del request.session["logueo"]
        messages.success(request, "session cerrada")
    except Exception as e:
        messages.warning(request, "ocurrio un error: ", e)
    return redirect('barberhouse:inicio')

def perfil(request):
    login = request.session.get('logueo', False)
    q = Usuarios.objects.get(pk = login[0])

    contexto = {"perfil": q}

    return render(request, 'barberhouse/usuarios/perfil.html', contexto)

def actualizarPerfil(request):
    if request.method == "POST":
        try:
            login = request.session.get('logueo', False)
            q = Usuarios.objects.get(pk = login[0])
            q.cedula_usuario = request.POST["cedula"]
            q.nombre = request.POST["nombre"]
            q.apellido = request.POST["apellido"]
            q.fecha_nacimiento = request.POST["fecha"]

            if q.correo != request.POST["correo"]:
                try:
                    c = Usuarios.objects.get(correo = request.POST["correo"])
                    raise Exception("Este correo ya existe")
                except Usuarios.DoesNotExist:
                    messages.debug(request, "--El resultado de la consulta es: OK--")
                    q.correo = request.POST["correo"]
            else:
                messages.debug(request, "--No hay cambios en el correo --")
                q.correo = request.POST["correo"]

            if request.POST["clave"] != "":
                q.clave = claveEncriptada(request.POST["clave"])
            q.save()
        except Usuarios.DoesNotExist:
            messages.error(request, "No existe el usuario...")    
        except Exception as e:
            messages.error(request, f'Error: {e}')
    else:
        messages.warning(request, "No Envio datos")

    return redirect('barberhouse:Perfil_Usuario')


# enviar correos
def sendMail(request):
    try:
        send_mail(
            'Mi coshi',
            'Mi muñeca hermosa, sabes que te amo tanto mi bebe y estoy tan orgulloso de ti, de ver la mujer ta luchadora que tengo a mi lado, de versad te felicito por estar cumpliendo tus metas, TE AMO MI FLAcA',
            'd4v1d1521@gmail.com',
            ['alexandraarenas0213@gmail.com'],
            fail_silently=False,
        )
        messages.info(request, "correo de prueba enviado con exito")
    except Exception as e:
        messages.error(request, f"error: {e}")
    return redirect('barberhouse:loginForm')
    


#Roles
def roles(request):
    
    login = request.session.get('logueo', False)
    if login and (login[3] == "Admin"):

        r = Rol.objects.all()
    
        p = Paginator(r,3 )
    
        page_number = request.GET.get('page')

        r = p.get_page(page_number)

        contexto = {'datos': r}
        return render(request, 'barberhouse/roles/listar_roles.html', contexto)
    else:
        if login and (login[3] != "Admin"):
            messages.warning(request, "Usted no está autorizado para éste módulo...")
            return redirect('barberhouse:inicio')
        else:
            messages.warning(request, "Debe iniciar sesión primero...")
            return redirect('barberhouse:loginForm')

    

def rolesBuscar(request):
    if request.method == "POST":

        q = roles.objects.filter(
            Q(nombre_rol__icontains = request.POST["buscar"])
        )

        p = Paginator(q, 20)
        p_number = request.GET.get('page')

        u = p.get_page(p_number)

        contexto = {'page_obj': u, 'Datos': request.POST["buscar"]}

        return render(request,'barberhouse/roles/listar_roles_ajax.html',contexto)
    else:
        messages.warning(request,"no se han enviado datos")
        return redirect('barberhouse:listarRoles')


def formularioRol(request):

    login = request.session.get('logueo', False)
    if login and (login[3] == "Admin"):

        return render(request, 'barberhouse/roles/crear_roles.html')
    else:
        if login and (login[3] != "Admin"):
            messages.warning(request, "Usted no está autorizado para éste módulo...")
            return redirect('barberhouse:inicio')
        else:
            messages.warning(request, "Debe iniciar sesión primero...")
            return redirect('barberhouse:loginForm')

def guardarRol(request):
    try:
        if request.method == "POST":
            r = Rol(
                nombre_rol = request.POST["Nombre"] 
            )
            r.save()
            messages.success(request, "Rol agregado correctamente")
            return redirect('barberhouse:listarRoles')
        else:
            messages.warning(request, "No se enviaron datos")   
    except Exception as e:
        messages.error(request,"Error: " + str(e))
        return redirect('barberhouse:listarRoles')


def editarRol(request,id):
    
    login = request.session.get('logueo', False)
    if login and (login[3] == "Admin"):

        e = Rol.objects.get(pk = id)
        contexto = {"datos": e}
        return render(request, 'barberhouse/roles/editar_roles.html', contexto)

    else:
        if login and (login[3] != "Admin"):
            messages.warning(request, "Usted no está autorizado para éste módulo...")
            return redirect('barberhouse:inicio')
        else:
            messages.warning(request, "Debe iniciar sesión primero...")
            return redirect('barberhouse:loginForm')


def actualizarRol(request):
    try:
        if request.method == "POST":
            r = Rol.objects.get(pk = request.POST["id"])

            r.nombre_rol = request.POST["Nombre"]

            r.save()

            messages.success(request, "Rol actualizado")
            return redirect('barberhouse:listarRoles')
        else:
            messages.warning(request,"No se enviaron datos")
            return redirect('barberhouse:listarRoles')
    except Exception as e:
        messages.error(request, "error: " + str(e))
        return redirect('barberhouse:listarRoles')

def eliminarRol(request,id):
    try:
        p = Rol.objects.get(pk = id)
        p.delete()
        
        return HttpResponseRedirect(reverse('barberhouse:listarRoles'))
    except Rol.DoesNotExist:
        return HttpResponse('ERROR: Rol no existe')
    except Exception as e:
        return HttpResponse(f'error: {e}')


        

#Usuarios
def usuarios(request):
    login = request.session.get('logueo', False)
    if login and (login[3] == "Admin"):

        u = Usuarios.objects.all()

        p = Paginator(u, 2)
        
        p_number = request.GET.get('page')

        u = p.get_page(p_number)

        contexto = {'datos': u}
        return render(request, 'barberhouse/usuarios/listar_usuarios.html', contexto)
    else:
        if login and login[3] != "Admin":
            messages.warning(request, "Usted no está autorizado para éste módulo...")
            return redirect('barberhouse:inicio')
        else:
            messages.warning(request, "Debe iniciar sesión primero...")
            return redirect('barberhouse:loginForm')

def usuariosBuscar(request):
    if request.method == "POST":

        q = Usuarios.objects.filter(
            Q(cedula__icontains = request.POST["buscar"])|
            Q(nombre__icontains = request.POST["buscar"])|
            Q(apellido__icontains = request.POST["buscar"])|
            Q(rol__icontains = request.POST["buscar"])
            )

        p = Paginator(q, 20)
        p_number = request.GET.get('page')

        u = p.get_page(p_number)

        contexto = {'page_obj': u, 'Datos': request.POST["buscar"]}

        return render(request,'barberhouse/usuarios/listar_usuario_ajax.html',contexto)
    else:
        messages.warning(request,"no se han enviado datos")
        return redirect('barberhouse:usuarios')


def usuariosFormulario(request):

    login = request.session.get('logueo', False)
    if login == False:
        
        return render(request, 'barberhouse/usuarios/registrar_cliente.html')

    elif login and (login[3] == "Admin"):

        r = Rol.objects.all()
        contexto = {'datos': r}
        return render(request, 'barberhouse/usuarios/crear_usuarios.html',contexto)
    
    else:
        if login and (login[3] != "Admin"):

proyecto_python/barberhouse/templates/barberhouse/servicios/crear_servicios.html
{% extends 'barberhouse/base.html' %}

{% block body  %}
<br/><br/>
<br/>
<h1>CREAR SERVICIO</h1>

<form style="text-align:center;" action="{% url 'barberhouse:guardar_servicio' %}" method="post">
    {% csrf_token %}

    <label for="">Nombre</label><br />
    <input type="text" class="form-control" name="nombre_servicio" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">Precio</label><br />
    <input type="number" class="form-control" name="precio" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">Promocion</label><br />
    <select class="form-control" name="promocion" style="width:70%; margin-left: auto; margin-right:auto;">

        {% if promocion %}
            
            {% for registro in promocion %}
                
                <option value="{{ registro.id }}">{{ registro.nombre_promocion }}</option>
                
            {% endfor %}

        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    
    </select><br/>
    
    <label for="">Empleado</label><br />
    <select class="form-control" name="empleado" style="width:70%; margin-left: auto; margin-right:auto;">

        {% if empleado %}
            
            {% for registro in empleado %}
                
                <option value="{{ registro.cedula_usuario }}">{{ registro.nombre }}</option>
                
            {% endfor %}

        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    
    </select><br/>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

{% endblock %}

proyecto_python/barberhouse/templates/barberhouse/servicios/editar_servicios.html
{% extends 'barberhouse/base.html' %}

{% block body  %}
<br/><br/>
<br/><br/>
<br/><br/>

<h1>EDITAR SERVICIO - <strong>{{ servicio.nombre_servicio }}</strong></h1>

<form style="text-align:center;" action="{% url 'barberhouse:actualizar_servicio' %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="id" value="{{ servicio.id }}"/>

    <label for="">Nombre</label><br />
    <input type="text" class="form-control" name="nombre_servicio" value="{{ servicio.nombre_servicio }}" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">Precio</label><br />
    <input type="number" class="form-control" name="precio" value="{{ servicio.precio }}" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">Promocion</label><br />
    <select class="form-control" name="promocion" value="{{ promocion.nombre_promocion }}" style="width:70%; margin-left: auto; margin-right:auto;">

        {% if promocion %}
            
            {% for registro in promocion %}
                
                <option value="{{ registro.id }}">{{ registro.nombre_promocion }}</option>
                
            {% endfor %}

        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    
    </select><br/>
    
    <label for="">Empleado</label><br />
    <select class="form-control" name="empleado" value="{{ empleado.nombre }}" style="width:70%; margin-left: auto; margin-right:auto;">

        {% if empleado %}
            
            {% for registro in empleado %}
                
                <option value="{{ registro.cedula_usuario }}">{{ registro.nombre }}</option>
                
            {% endfor %}

        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    
    </select><br/>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

{% endblock %}

proyecto_python/barberhouse/templates/barberhouse/servicios/listar_servicios.html
{% extends 'barberhouse/base.html' %}

{% block body  %}

{% if datos %}
    <h1>SERVICIOS</h1>
    <div class="listado">
        <input class="form-control me-2 buscar" type="search" name="buscar" id="buscar" placeholder="Buscar" aria-label="Search" value="{{ Datos }}" onkeyup="buscarA('{% url 'barberhouse:Buscar_usuario' %}');">
        {% csrf_token %}
        <table id="example" class="ui celled table " style="width:100%">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Nombre</td>
                    <td>PRECIO</td>
                    <td>PROMOCION</td>
                    <td>EMPLEADO</td>
                    <td>EDITAR</td>
                    <td>ELIMINAR</td>
                </tr>
            </thead>
            <tbody>

                {% for registro in datos %}
                <tr>
                    <td>{{ registro.id }}</td>
                    <td>{{ registro.nombre_servicio }}</td>
                    <td>{{ registro.precio }}</td>
                    <td>{{ registro.promocion }}</td>
                    <td>{{ registro.empleado }}</td>
                    <td>
                        <a class="btn btn-info botones" href="{% url 'barberhouse:editar_servicio' registro.id %} ">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path
                            d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                            d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                            </svg>
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-danger botones" onclick="confirmarEliminar('{% url 'barberhouse:eliminar_servicio' registro.id %}')"; >
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-trash-fill" viewBox="0 0 16 16">
                            <path
                            d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                            </svg>
                        </a>
                    </td>
                </tr>
    
                {% endfor %}
            </tbody>
            

        </table>
        <a class="btn btn-primary crear botones" href="{% url 'barberhouse:crear_servicio' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>
        </a>

        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item {% if not datos.has_previous %} disabled {% endif %}">
                    
                    <a class="page-link" {% if datos.has_previous %} href="?page={{ datos.previous_page_number }} " {% endif %}  >Anterior</a>
                    
                </li>
                {% for i in "d"|rjust:datos.paginator.num_pages|make_list %}

                <li class="page-item {% if forloop.counter == datos.number %} active {% endif %}"><a class="page-link" aria-current="page " href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

                {% endfor %}

                <li class="page-item {% if not datos.has_next %} disabled {% endif %} ">
                    <a class="page-link" {% if datos.has_next %} href="?page={{ datos.next_page_number }}" {% endif %} >siguiente</a>
                </li>
            </ul>
        </nav> 
    </div>

{% else %}
    <h1>No hay datos</h1>
{% endif %}

{% endblock %}